filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/development.log
      - /logs/production.log
    fields:
      service: backend
      application: prod-server
    fields_under_root: true
    # Handle multi-line JSON (Winston pretty-prints with 4 spaces)
    multiline.pattern: '^\{'
    multiline.negate: true
    multiline.match: after
    # Parse JSON directly in Filebeat
    processors:
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
      - script:
          lang: javascript
          source: >
            function process(event) {
              var logPath = event.Get("log.file.path");
              if (logPath && logPath.includes("development.log")) {
                event.Put("environment", "development");
              } else if (logPath && logPath.includes("production.log")) {
                event.Put("environment", "production");
              }
            }

# REMOVE ELASTICSEARCH OUTPUT - Send to Logstash instead
output.logstash:
  hosts: ["logstash:5044"]

# Remove direct Elasticsearch configuration
setup.ilm:
  enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
