services:
  frontend:
    build:
      context: ./prod-client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - backend
    env_file:
      - ./prod-client/.env
    networks:
      - app-network

  backend:
    build:
      context: ./prod-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      mongodb:
        condition: service_healthy
      mongodb-init:
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy
    env_file:
      - ./prod-server/.env.production
    environment:
      - NODE_ENV=production
    volumes:
      # Mount logs directory to make it accessible to Filebeat
      - ./prod-server/logs:/app/logs:rw
    networks:
      - app-network
    restart: unless-stopped

 
networks:
  app-network:
    driver: bridge

volumes:

  elasticsearch_data:
    driver: local
  filebeat_data:
    driver: local
