# docker-compose.yml
version: "3.9"

services:
  frontend:
    build:
      context: ./prod-client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - backend
    env_file:
      - ./prod-client/.env
    networks:
      - app-network

  backend:
    build:
      context: ./prod-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./prod-server/.env.production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge